### ISSUE TITLE
Publish first release

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-ebpf#139]
As per title: publish a first open source release of the eBPF collector.

This issue works as a checklist for the release:
* [x] Adopt a versioning scheme for the release numbering
* [x] Create a first tag for the release
* [x] Create release notes for the release

Not included are to build or deliver any binaries, the first release can be source only.

**Comment by atoulme** [comment]
We have a release procedure doc but it's not contributed to the repository yet, to be added as part of this work.

**Comment by atoulme** [comment]
It looks like we can close this issue. @bjandras would you agree?

**Comment by bjandras** [comment]
Agreed, closing.
