### ISSUE TITLE
Integrate the opentelemetry-ebpf project with the OpenTelemetry helm chart

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-ebpf#186]
### Is your feature request related to a problem? Please describe.

See #55 for original question: we would like to see the eBPF project integrate with a helm chart as an example.

### Describe the solution you'd like

 Right now, we have an integration with a vendor with https://github.com/signalfx/splunk-otel-collector-chart but it would be great to add this to https://github.com/open-telemetry/opentelemetry-helm-charts.

**Comment by nicolastakashi** [comment]
Hey @atoulme may I work on that?

**Comment by atoulme** [comment]
It's yours! We discussed just taking whatever we have in the splunk repo and upstream it to opentelemetry. Please feel free to go ahead.

**Comment by JaredTan95** [comment]
This issue can be closed, as https://github.com/open-telemetry/opentelemetry-helm-charts/pull/855 merged.

**Comment by atoulme** [comment]
Indeed, thanks @nicolastakashi !
