### ISSUE TITLE
[Question] Is there a k8s deployment or daemonset yaml example?

### ISSUE THREAD

**Issue by vakalapa** [open-telemetry/opentelemetry-ebpf#55]
New to this project. 
I did not find a discussions section, so raising an issue. Please direct me to any other conversation channel which you might be using. 

I am looking to test and see the capabilities of this project. Is there a daemonset yaml example, if not i can create one and contribute back.

**Comment by jimwsplk** [comment]
There are examples at  https://github.com/Flowmill/splunk-otel-network-explorer-chart currently, which will likely be relocated at some point.

Also, feel free to join the #otel-ebpf CNCF Slack channel.
https://communityinviter.com/apps/cloud-native/cncf

**Comment by jimwsplk** [comment]
The helm chart mentioned above is no longer active.  The current location is https://github.com/signalfx/splunk-otel-collector-chart

**Comment by atoulme** [comment]
The question is answered and work continues in #186.
